language: php
sudo: required
dist: trusty

php:
  - 7.2

addons:
  chrome: stable

install:
  - touch database/testing_browser.sqlite
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - travis_retry npm install
  - wget -N https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip -P ~/
  - unzip chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - php artisan key:generate

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk