language: php
sudo: required
dist: trusty

php:
  - 7.2

addons:
  chrome: stable

install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
  - touch database/testing_browser.sqlite
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - travis_retry npm install
  - php artisan key:generate
  - php artisan dusk:update
  - sudo chmod a+x ./vendor/laravel/dusk/bin/chromedriver-linux
  - ./vendor/laravel/dusk/bin/chromedriver-linux &

before_script:
  - google-chrome-stable --headless --disable-gpu --window-size=1024,768 --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk